version: '3'

services:
  mssql-server:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "mssql_password"
      ACCEPT_EULA: "Y"

  cassandra:
    image: "cassandra:latest"
    ports:
      - "9042:9042"
