"""
Main dashboard for admin
"""
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from gui import AdminLogin


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets (2)")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def dashboard(caller):
    caller.destroy()
    window = Tk()
    window.title('C-Connect')
    window.geometry("411x891")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 891,
        width = 411,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        205.0,
        392.0,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        120.0,
        231.0,
        image=image_image_2
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        206.0,
        373.0,
        image=image_image_3
    )

    canvas.create_text(
        51.0,
        215.0,
        anchor="nw",
        text="Recent Announcements",
        fill="#333333",
        font=("Spartan Medium", 11 * -1)
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=289.0,
        y=460.0,
        width=62.0,
        height=40.0
    )

    image_image_4 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    image_4 = canvas.create_image(
        95.0,
        115.0,
        image=image_image_4
    )

    canvas.create_text(
        44.0,
        531.0,
        anchor="nw",
        text="Communication",
        fill="#333333",
        font=("Spartan SemiBold", 18 * -1)
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=220.0,
        y=600.0,
        width=150.0,
        height=85.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.place(
        x=41.0,
        y=600.0,
        width=150.0,
        height=85.0
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        208.0,
        271.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0
    )
    entry_1.place(
        x=65.0,
        y=256.0,
        width=286.0,
        height=28.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        208.0,
        304.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0
    )
    entry_2.place(
        x=65.0,
        y=289.0,
        width=286.0,
        height=28.0
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        208.0,
        337.0,
        image=entry_image_3
    )
    entry_3 = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0
    )
    entry_3.place(
        x=65.0,
        y=322.0,
        width=286.0,
        height=28.0
    )

    entry_image_4 = PhotoImage(
        file=relative_to_assets("entry_4.png"))
    entry_bg_4 = canvas.create_image(
        208.0,
        371.0,
        image=entry_image_4
    )
    entry_4 = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0
    )
    entry_4.place(
        x=65.0,
        y=356.0,
        width=286.0,
        height=28.0
    )

    entry_image_5 = PhotoImage(
        file=relative_to_assets("entry_5.png"))
    entry_bg_5 = canvas.create_image(
        208.0,
        406.0,
        image=entry_image_5
    )
    entry_5 = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0
    )
    entry_5.place(
        x=65.0,
        y=391.0,
        width=286.0,
        height=28.0
    )

    entry_image_6 = PhotoImage(
        file=relative_to_assets("entry_6.png"))
    entry_bg_6 = canvas.create_image(
        208.0,
        440.0,
        image=entry_image_6
    )
    entry_6 = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0
    )
    entry_6.place(
        x=65.0,
        y=425.0,
        width=286.0,
        height=28.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_4 clicked"),
        relief="flat"
    )
    button_4.place(
        x=41.0,
        y=709.0,
        width=150.0,
        height=85.0
    )

    canvas.create_text(
        145.0,
        99.0,
        anchor="nw",
        text="Welcome to your",
        fill="#333333",
        font=("Spartan", 24 * -1)
    )

    canvas.create_text(
        158.0,
        139.0,
        anchor="nw",
        text="Dashboard!",
        fill="#FF6338",
        font=("Spartan", 32 * -1)
    )

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: AdminLogin.portal(window),
        relief="flat"
    )
    button_5.place(
        x=17.0,
        y=60.0,
        width=21.0,
        height=21.0
    )

    image_image_5 = PhotoImage(
        file=relative_to_assets("line.png"))
    image_5 = canvas.create_image(
        208.0,
        286.0,
        image=image_image_5
    )

    image_image_6 = PhotoImage(
        file=relative_to_assets("line.png"))
    image_6 = canvas.create_image(
        208.0,
        320.0,
        image=image_image_6
    )

    image_image_7 = PhotoImage(
        file=relative_to_assets("line.png"))
    image_7 = canvas.create_image(
        207.0,
        354.0,
        image=image_image_7
    )

    image_image_8 = PhotoImage(
        file=relative_to_assets("line.png"))
    image_8 = canvas.create_image(
        208.0,
        388.0,
        image=image_image_8
    )

    image_image_9 = PhotoImage(
        file=relative_to_assets("line.png"))
    image_9 = canvas.create_image(
        208.0,
        422.0,
        image=image_image_9
    )

    image_image_10 = PhotoImage(
        file=relative_to_assets("line.png"))
    image_10 = canvas.create_image(
        207.0,
        456.0,
        image=image_image_10
    )

    image_image_11 = PhotoImage(
        file=relative_to_assets("image_11.png"))
    image_11 = canvas.create_image(
        56.0,
        360.0,
        image=image_image_11
    )
    window.resizable(False, False)
    window.mainloop()
