"""
This file raises an exception when username or password is incorrect
"""

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from gui import StudentLogin, AdminLogin


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def error(caller):
    caller.destroy()
    window = Tk()
    window.title('C-Connect')
    window.geometry("411x891")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 400,
        width = 400,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        205.0,
        373.0,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_7.png"))
    image_2 = canvas.create_image(
        205.0,
        225.0,
        image=image_image_2
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: StudentLogin.portal(window) ,
        relief="flat"
    )
    button_1.place(
        x=108.0,
        y=304.0,
        width=200.0,
        height=60.0
    )

    canvas.create_text(
        95.0,
        202.0,
        anchor="nw",
        text="ID or Password Incorrect",
        fill="#000000",
        font=("JosefinSansRoman Regular", 20 * -1)
    )

    canvas.create_text(
        149.0,
        100.0,
        anchor="nw",
        text="ERROR",
        fill="#000000",
        font=("JosefinSansRoman Regular", 32 * -1)
    )
    window.resizable(False, False)
    window.mainloop()
