
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import gui.gen


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./rassets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def read_win(caller,mail):
    caller.destroy()
    window = Tk()
    window.title('C-Connect')

    window.geometry("411x891")
    window.configure(bg = "#FFFFFF")

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 891,
        width = 411,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        205.0,
        445.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1"),
        relief="flat"
    )
    button_1.place(
        x=17.0,
        y=60.0,
        width=21.0,
        height=21.0
    )

    canvas.create_text(
        38.0,
        123.0,
        anchor="nw",
        text="Sender:",
        fill="#000000",
        font=("Spartan Medium", 16 * -1)
    )

    canvas.create_text(
        38.0,
        197.0,
        anchor="nw",
        text="Subject:",
        fill="#000000",
        font=("Spartan Medium", 16 * -1)
    )

    canvas.create_rectangle(
        125.0,
        116.0,
        375.0,
        160.0,
        fill="#FFFFFF",
        outline="")

    canvas.create_rectangle(
        125.0,
        184.0,
        375.0,
        226.0,
        fill="#FFFFFF",
        outline="")

    canvas.create_rectangle(
        38.0,
        263.0,
        375.0,
        776.0,
        fill="#FFFFFF",
        outline="")

    canvas.create_text(
        135.0,
        123.0,
        anchor="nw",
        text=mail.sender,
        fill="#000000",
        font=("Spartan Medium", 16 * -1)
    )
    canvas.create_text(
        135.0,
        197.0,
        anchor="nw",
        text=mail.subject,
        fill="#000000",
        font=("Spartan Medium", 16 * -1)
    )

    canvas.create_text(
        48.0,
        270.0,
        anchor="nw",
        text=mail.body,
        fill="#000000",
        font=("Spartan Medium", 16 * -1)
    )
    window.resizable(False, False)
    window.mainloop()
