"""
Main dashboard for students
"""
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from gui import gen
import mainmenu


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets (1)")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def dashboard(caller,userD):
    caller.destroy()
    window = Tk()
    window.title('C-Connect')
    window.geometry("411x891")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 891,
        width = 411,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        205.0,
        373.0,
        image=image_image_1
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        108.0,
        231.0,
        image=image_image_2
    )

    image_image_3 = PhotoImage(
        file=relative_to_assets("image_3.png"))
    image_3 = canvas.create_image(
        206.0,
        319.0,
        image=image_image_3
    )

    canvas.create_text(
        51.0,
        216.0,
        anchor="nw",
        text="Important Notice",
        fill="#333333",
        font=("Spartan Medium", 11 * -1)
    )

    canvas.create_text(
        43.0,
        422.0,
        anchor="nw",
        text="Academic Circulars",
        fill="#333333",
        font=("Spartan SemiBold", 18 * -1)
    )

    image_image_4 = PhotoImage(
        file=relative_to_assets("image_4.png"))
    image_4 = canvas.create_image(
        201.0,
        283.0,
        image=image_image_4
    )

    image_image_5 = PhotoImage(
        file=relative_to_assets("image_5.png"))
    image_5 = canvas.create_image(
        201.0,
        319.0,
        image=image_image_5
    )

    image_image_6 = PhotoImage(
        file=relative_to_assets("image_6.png"))
    image_6 = canvas.create_image(
        201.0,
        353.0,
        image=image_image_6
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=222.0,
        y=494.0,
        width=150.0,
        height=140.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=37.0,
        y=662.0,
        width=150.0,
        height=140.0
    )

    button_image_3 = PhotoImage(
        file=relative_to_assets("button_3.png"))
    button_3 = Button(
        image=button_image_3,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_3 clicked"),
        relief="flat"
    )
    button_3.place(
        x=222.0,
        y=662.0,
        width=150.0,
        height=140.0
    )

    button_image_4 = PhotoImage(
        file=relative_to_assets("button_4.png"))
    button_4 = Button(
        image=button_image_4,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_4 clicked"),
        relief="flat"
    )
    button_4.place(
        x=270.0,
        y=426.0,
        width=100.0,
        height=33.0
    )
    def general(window,userD):
        notices = mainmenu.display(userD,1)
        print (notices[0].subject)
        gen.notif(window,userD,notices)

    button_image_5 = PhotoImage(
        file=relative_to_assets("button_5.png"))
    button_5 = Button(
        image=button_image_5,
        borderwidth=0,
        highlightthickness=0,
        command = lambda: general(window,userD),
        relief="flat"
    )
    button_5.place(
        x=37.0,
        y=494.0,
        width=150.0,
        height=140.0
    )

    button_image_6 = PhotoImage(
        file=relative_to_assets("button_6.png"))
    button_6 = Button(
        image=button_image_6,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_6 clicked"),
        relief="flat"
    )
    button_6.place(
        x=17.0,
        y=60.0,
        width=21.0,
        height=21.0
    )

    canvas.create_text(
        145.0,
        99.0,
        anchor="nw",
        text="Welcome to your",
        fill="#333333",
        font=("Spartan", 24 * -1)
    )

    canvas.create_text(
        159.0,
        139.0,
        anchor="nw",
        text="Dashboard!",
        fill="#FF6338",
        font=("Spartan", 32 * -1)
    )

    image_image_7 = PhotoImage(
        file=relative_to_assets("image_7.png"))
    image_7 = canvas.create_image(
        90.0,
        124.0,
        image=image_image_7
    )

    image_image_8 = PhotoImage(
        file=relative_to_assets("image_8.png"))
    image_8 = canvas.create_image(
        370.0,
        71.0,
        image=image_image_8
    )

    button_image_7 = PhotoImage(
        file=relative_to_assets("button_7.png"))
    button_7 = Button(
        image=button_image_7,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_7 clicked"),
        relief="flat"
    )
    button_7.place(
        x=289.0,
        y=357.0,
        width=62.0,
        height=34.0
    )

    image_image_9 = PhotoImage(
        file=relative_to_assets("image_9.png"))
    image_9 = canvas.create_image(
        55.0,
        312.0,
        image=image_image_9
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png"))
    entry_bg_1 = canvas.create_image(
        205.5,
        268.0,
        image=entry_image_1
    )
    entry_1 = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0
    )
    entry_1.place(
        x=60.0,
        y=256.0,
        width=291.0,
        height=22.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png"))
    entry_bg_2 = canvas.create_image(
        205.5,
        304.0,
        image=entry_image_2
    )
    entry_2 = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0
    )
    entry_2.place(
        x=60.0,
        y=292.0,
        width=291.0,
        height=22.0
    )

    entry_image_3 = PhotoImage(
        file=relative_to_assets("entry_3.png"))
    entry_bg_3 = canvas.create_image(
        205.5,
        338.0,
        image=entry_image_3
    )
    entry_3 = Entry(
        bd=0,
        bg="#FFFFFF",
        highlightthickness=0
    )
    entry_3.place(
        x=60.0,
        y=326.0,
        width=291.0,
        height=22.0
    )
    window.resizable(False, False)
    window.mainloop()
